name: IAAC-WORKFLOW-APPT
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    uses: edgarflores33/terraform/.github/workflows/deploy.yaml@main          
    # secrets:
    #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    # with:
    #     path_tf : './sus-ciam-dev'
    
    # terraform-destroy:
    #     uses: edgarflores33/terraform/.github/workflows/workflow_schedule.yaml@main
        # secrets:
        #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        # with:
        #      path_tf : './sus-ciam-dev'

####################################################################################################
